#Exploration analysis

##Traffic data


```{r }

##Traffic stop
##Analyze the highest porpose of the arrestation ( between female and male)

Traffic_stop_2<-Traffic_stop_2 %>% filter(Purpose != "Total" & Purpose != "FemaleTotal" & Purpose != "MaleTotal")

ggplot(Traffic_stop_2, aes(x=Purpose, y= Traffic_stop_2$`Total By Ethnicity`, fill= Gender)) +
  geom_bar(stat = "identity") +
  facet_wrap(~Year) +
  labs(title = "The main purpose is the speed limit violation" ,subtitle = "for the year 2014-2015", x= "Purpose", y= "Total stop by race")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

```

```{r }
##Analyze the highest purpose of the arrestation (between black and white people)

 Traffic_stop_2 <- Traffic_stop_2 %>% mutate(Pro_Black_white = Black/White)
 Traffic_stop_2$Pro_Black_white[is.nan(Traffic_stop_2$Pro_Black_white)]<-0
 
 
Traffic_stop_2 %>% group_by(Purpose, Gender) %>%
ggplot(aes(x= reorder(Purpose,Traffic_stop_2$Pro_Black_white) , y= Traffic_stop_2$Pro_Black_white)) +
  geom_bar(stat = "identity") +
  facet_grid(Gender~Year) +
  labs(title = "More black arrested for the investigation purpose" ,subtitle = "for the year 2014-2015", x= "Purpose", y= "Ratio Black/White")+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
   scale_y_continuous(labels = scales::percent) +
  theme( strip.background  = element_blank(),
                      panel.grid.major = element_line(colour = "black"),
                      panel.border = element_blank(),
                      axis.ticks = element_blank(),
                      panel.grid.minor.x=element_blank(),
                      panel.grid.major.x=element_blank() )

```

## Police arrested made.
```{r }
#Analzye the number of arrestation over the year in relation to the race.

Police_arrest_made<- Police_arrest_made %>% mutate(month=month(`Date of Arrest`), year= year(`Date of Arrest`))


graph1 = Police_arrest_made %>% count(`Arrestee's Race`, month, year) %>%
  filter(!is.na(`Arrestee's Race`))

ggplot(graph1,aes(x=month,y=n, fill= factor(`Arrestee's Race`), col= `Arrestee's Race`)) +
  geom_line() +
  facet_grid(~year)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position ="bottom") +
  theme(legend.key.size = unit(0.5, "cm")) +
  scale_x_continuous( breaks = seq(1,12,by=5)) +
  labs(title = "Number of arrestation", subtitle = "year 2010 to 2019", x= "Date",y="Number of arrestation")

```

```{r }
## More focus on the ration of the black and white arrested 
##Same plot as before but only with the white and black people and plot the difference

graph2= Police_arrest_made %>% filter(`Arrestee's Race`=="White" | `Arrestee's Race` =="Black") %>% count(`Arrestee's Race`, month, year)

ggplot(graph2, aes(x=month,y=n)) +
  geom_line(size=1, aes(color=`Arrestee's Race`)) +
  geom_point(aes(color=`Arrestee's Race`)) +
  facet_grid(~year) +
  stat_summary(fun.y = diff, geom = "bar") +
  theme(legend.position ="bottom")  +
  scale_x_continuous( breaks = seq(1,12,by=5))

```

```{r }
##Same plot as before, but only considering the year and not the month

graph3= Police_arrest_made %>% filter(`Arrestee's Race`=="White" | `Arrestee's Race` =="Black") %>% count(`Arrestee's Race`, year,)

ggplot(graph3, aes(x=year,y=n)) +
  geom_line(size=1, aes(color=`Arrestee's Race`)) +
  geom_point(aes(color=`Arrestee's Race`)) +
  stat_summary(fun.y = diff, geom = "bar") +
  theme(legend.position ="bottom")  +
  scale_x_continuous( breaks = seq(1,12,by=5))
```

```{r }
##Number of arrestation taking into account the race and the gender

graph4 = Police_arrest_made %>% count(`Arrestee's Race`, `Arrestee's Gender`, year) %>%
  filter(!is.na(`Arrestee's Race`))

ggplot(graph4,aes(x=year,y=n, fill= factor(`Arrestee's Race`), col= `Arrestee's Race`)) +
  geom_line() +
  facet_grid(~`Arrestee's Gender`)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position ="bottom") +
  theme(legend.key.size = unit(0.5, "cm"))  +
  labs(title = "Number of arrestation", subtitle = "year 2010 to 2019", x= "Date",y="Number of arrestation") +
  scale_x_continuous( breaks = seq(2010,2019,by=1))
```


```{r }

summary(Police_arrest_made)
meanAgeArrestee <- Police_arrest_made %>%
  group_by(`Arrestee's Race`)%>%
  summarize(MEDIANAGR = median(`Arrestee's Age`))
meanAgeArrestee
```

```{r }
Police_arrest_made %>%
  group_by(`Arrestee's Race`) %>%
  count() %>%
  arrange(desc(n)) %>%
    kable(caption= "Number of Arrestees per race", digits=2) %>%
  kable_styling(bootstrap_options = "striped")
``` 
 
```{r }
 Police_arrest_made %>%
  ggplot(aes(`Arrestee's Race`, `Arrestee's Age` )) + 
  geom_point(aes(color =  Police_arrest_made$`Arrestee's Gender`)) +
  geom_hline(yintercept = 33, color = "black") +
  geom_hline(yintercept = 28, color = "bisque2") +
  geom_hline(yintercept = 27, color = "orange") +
  geom_hline(yintercept = 25, color = "yellow") +
   labs(title = "Age of Arrestee per race",subtitle = "",caption = "Police_demographics.csv", x= "Race", y="Age of arrestee")
```

```{r }
## Arrestation Age by ethnicity

ggplot(Police_arrest_made, aes(x=Police_arrest_made$`Arrestee's Race`, y=Police_arrest_made$`Arrestee's Age` )) +
  geom_boxplot() +
  labs(x= "Arrestee's Race", y= "Age",
       title = "Age corresponding to each Ethnicity",
       subtitle = "Arrested pepople between 2010 and 2019")
```

```{r }
##Analyze the type of arrestation taking into account the race

graph5 = Police_arrest_made %>% count(`Arrestee's Race`, `Type of Arrest`, year) %>%
  filter(!is.na(`Type of Arrest`))

ggplot(graph5,aes(x=year,y=n, fill= factor(`Arrestee's Race`), col= `Arrestee's Race`)) +
  geom_line() +
  facet_grid(~`Type of Arrest`)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position ="bottom") +
  theme(legend.key.size = unit(0.5, "cm"))  +
  labs(title = "Different pattern for each type of arrestation", subtitle = "year 2010 to 2019", x= "Date",y="Number of arrestation") +
  scale_x_continuous( breaks = seq(2010,2019,by=1))

```


## Incident reports

```{r }

Incident_reports<- Incident_reports %>% mutate(month=month(`Date of Occurrence`), year= year(`Date of Occurrence`))

graph6 = Incident_reports %>%filter(year>=2010) %>% count(`Victim Race`, `Victim Gender` , year) %>% filter(`Victim Gender`=="F" | `Victim Gender`=="M")

ggplot(graph6,aes(x=year,y=n, fill= factor(`Victim Race`), col= `Victim Race`)) +
  geom_line() +
  facet_grid(~`Victim Gender`)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position ="bottom") +
  theme(legend.key.size = unit(0.5, "cm"))  +
  labs(title = "White people are the Major victim ", subtitle = "year 2010 to 2019", x= "Date",y="Number of Victim") 
```

```{r , echo=FALSE}
Incident_reports%>%
  group_by(`Victim Race`)  %>%
  mutate(DELAYReported = `Date of Report`- `Date of Occurrence`, DELAYArrested = `Date Found`- `Date of Occurrence`) %>%
  filter( DELAYArrested < 20000 & DELAYArrested > 100) %>%
  ggplot(aes( `Victim Race`, DELAYArrested )) +
  geom_boxplot()
# By filtering de la sorte, we can see that there are more outliers for white people but and there is a greater variance in delay time for the arrestation whenthe case concern black people.

```

```{r }
##Employee demographics in the current of october 2016

graph7 = Employee_demographics %>% count(Gender,Race) %>% filter(Race != "M")
  

ggplot(graph7,aes(x=Race,y=n)) +
  geom_bar(stat = "identity") +
  facet_grid(~Gender)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position ="bottom") +
  theme(legend.key.size = unit(0.5, "cm"))  +
  labs(title = "Majority of White employee", subtitle = "Current of the year 2016", x= "Race",y="Number of employee") 

```


```{r }
# Employee Demographics
Employee_demographics %>%
  group_by(`Job Class Description`) %>%
  count(`Job Class Description`) %>% 
  arrange(desc(n)) %>%
  kable(caption= "Profession of the police officers by frequency", digits=2) %>%
  kable_styling(bootstrap_options = "striped")
```

```{r }
#Comupting the mean for the next plot
meanM<- Employee_demographics%>%
  group_by(Gender) %>%
  summarize(MEANSERVICE = mean(`Service Years`))

Employee_demographics %>%
  ggplot(aes(`Job Class Description`,`Service Years`)) + 
  geom_point(aes(color = Gender)) +
  geom_hline(yintercept = 14.24603, color = "darkblue") +
  geom_hline(yintercept = 12.02083, color = "pink") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size =6)) 
   labs(title = "Service length per position and gender",subtitle = "The average service is slighty longer for men,n/women have greater variance among year of service",caption = "Employee_demographics.csv", x= "Positions", y="Year of service")
```


```{r}
 #Computing the mean service length per race
meanR<- Employee_demographics%>%
  group_by(Race) %>%
  summarize(MEANSERVICE = mean(`Service Years`))
meanR
Employee_demographics %>%
  ggplot(aes(`Job Class Description`,`Service Years`)) + 
  geom_point(aes(color = Race)) +
  geom_hline(yintercept = 13.309502, color = "black") +
  geom_hline(yintercept = 13.95312, color = "bisque2") +
  geom_hline(yintercept = 7, color = "red") +
  geom_hline(yintercept = 6, color = "orange") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size =6)) +
   labs(title = "Service length per position and gender",subtitle = "The average service is slighty longer for men,n/women have greater variance among year of service",caption = "Employee_demographics.csv", x= "Positions", y="Year of service")
 
```

##Victim and Arrest distribution

```{r}
Police_arrest_made$`Date of Arrest`

test<-left_join(Incident_reports, Police_arrest_made, by = c("Date of Occurrence"="Date of Arrest"))

graph8 <- test %>%filter(year.x>=2010) %>% count(`Victim Race`, `Victim Gender` , year.x) %>% filter(`Victim Gender`=="F" | `Victim Gender`=="M") %>% filter(`Victim Race`=="Black")

graph9 <- test %>% filter(year.x>=2010) %>% count(`Arrestee's Race`, `Arrestee's Gender`,year.x) %>% filter(`Arrestee's Gender`=="F" | `Arrestee's Gender`=="M" ) %>%  filter(`Arrestee's Race`=="Black")


ggplot() +
  geom_line(aes(x=year.x,y=n,col=`Victim Race`), data = graph8) +
  geom_line(aes(x=year.x, y=n,col=`Arrestee's Race`), data = graph9)


ggplot(graph6,aes(x=year,y=n, fill= factor(`Victim Race`), col= `Victim Race`)) 
  geom_line() +
  facet_grid(~`Victim Gender`)+
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(legend.position ="bottom") +
  theme(legend.key.size = unit(0.5, "cm"))  +
  labs(title = "White people are the Major victim ", subtitle = "year 2010 to 2019", x= "Date",y="Number of Victim") 


```

<!--chapter:end:Exploration_analysis.Rmd-->



## Loading all the library
## Loading the data

<!--chapter:end:Introduction.Rmd-->




<!--chapter:end:Modelisation.Rmd-->

`r if (knitr:::is_html_output()) '
# References {-}
'`

<!--chapter:end:references.Rmd-->

