#Introduction


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading all the library

```{r }
library(readr)
library(tidyverse)
library(lubridate)
library(kableExtra)
```

## Loading the data

```{r }
library(readr)

Traffic_stop<- read_delim("data/drivers-and-passengers-searched-by-sex-race-and-ethnicity.csv",";", escape_double = FALSE, trim_ws = TRUE)

 Traffic_stop_2<-read_delim("data/initial-purpose-of-traffic-stop-by-drivers-sex-race-and-ethnicity.csv", ";", escape_double = FALSE, trim_ws = TRUE)
 
Police_arrest_made <- read_delim("data/police-arrests-made.csv",";", escape_double = FALSE, trim_ws = TRUE)
 
Employee_demographics<- read_delim("data/police-employee-demographics.csv",";", escape_double = FALSE, trim_ws = TRUE)

Incident_reports <-  read_delim("data/police-incident-reports-written.csv",";", escape_double = FALSE, trim_ws = TRUE)


```

##Cleaning the data

```{r }
  Police_arrest_made <- Police_arrest_made%>% 
   mutate( `Drugs or Alcohol Present` = fct_collapse(`Drugs or Alcohol Present`,
    "Yes"="Y",
    "No"="N",
    "Unknown"="U"
    )) %>%
   mutate(`Arrestee's Race` = fct_collapse(`Arrestee's Race`,
    "Asian"="A",
    "Black"="B",
    "Hispanic"="H",
    "Native American"="I",
    "Other" ="O",
    "Unknown"="U",
    "White"="W")) %>%
  mutate(`Arrestee's Gender`=fct_collapse(`Arrestee's Gender`,
        "Female"="F",
        "Male"="M"))

  
Incident_reports<- Incident_reports%>% 
  mutate(`Victim Race` = fct_collapse(`Victim Race`,
    "Asian"="A",
    "Black"="B",
    "Hispanic"="H",
    "Native American"="I",
    "Other" ="O",
    "Unknown"="U",
    "White"="W"))

Employee_demographics<- Employee_demographics %>%
  mutate(Race = fct_collapse(Race,
    "Asian"="A",
    "Black"="B",
    "Hispanic"="H",
    "Native American"="I",
    "Other" ="O",
    "Unknown"="U",
    "White"="W"))


```
